# Nixpacks 配置
# https://nixpacks.com/docs/configuration

[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y curl iptables jq",
]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
]

[start]
cmd = "./start.sh"

[environment]
PORT = "8003"